spring:
  application:
    name: loyaltyone-ms
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      #in milliseconds TTL 30*1000=30s
      time-to-live: 30000
  redis:
    host: 192.168.99.100
    port:  6379

mysql:
  datasource:
    #change ip localhost or mysql ip instead of 192.168.99.100
    url: jdbc:mysql://192.168.99.100:3306/demo
    username: root
    password: admin@123
    driver-class-name: com.mysql.jdbc.Driver

weather-api:
  url: https://api.openweathermap.org/data/2.5/weather
  appKey: be80e05ba26c537e5d6111ad81fb5127

#this will use for server monitoring
management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,threaddump,prometheus,heapdump"