---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: development
    app: loyaltyone-api
    tier: backend
  name: loyaltyone-api-ms
  namespace: development
spec:
  type: NodePort
  selector:
    app: loyaltyone-api
  ports:
  - name: api
    port: 8080
    targetPort: 8080

